### ISSUE TITLE
Example of Using the Redis Upstash API with Pure Javascript

### ISSUE THREAD

**Issue by jonasmartins-dev** [upstash/redis-examples#8]
I would like to contribute an Example of Using the Redis Upstash API with Pure Javascript.

Here is the example repository [https://github.com/jonasmartins-dev/todo-redis-upstash](https://github.com/jonasmartins-dev/todo-redis-upstash).

**Comment by enesakar** [comment]
hey @jonasmartins-dev , sure, send a PR.

**Comment by chronark** [comment]
Closing this, due to inactivity.
We'd still love your example. please just open a new issue.
